### ISSUE TITLE
fedimg seems to be stuck during initial AMI upload in us-east-1 region

### ISSUE THREAD

**Issue by sinnykumari** [fedora-infra/fedimg#106] opened 2018-04-21 18:09 UTC
From past two days, cloud AMIs upload for Fedora nightly composes seems to be stuck at uploading AMI to the very first region which is us-east-1.

Log messages say "[fedimg.uploader    INFO] AWS EC2Service process is completed." but, it doesn't look like upload really got completed.

**Comment by sayanchowdhury** [comment] 2018-04-22 12:50
@sinnykumari The issue is that AWS isn't returning the volume-id hence the process is breaking off, @davdunc is working with the team to find out the issue

**Comment by sayanchowdhury** [comment] 2018-05-02 16:18
This issue has been fixed been now. Going ahead and closing the issue

**Closed by sayanchowdhury** 2018-05-02 16:18 UTC
Labels: Crash, Critical
