### ISSUE TITLE
support for updates and updates-testing composes

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/fedimg#125] opened 2018-04-30 13:38 UTC
We are going to start making qcow image artifacts in our updates and updates-testing compose runs. We need to be able to pick these up in fedimg so they can be uploaded to AWS. For updates-testing runs maybe we don't default to uploading them to AWS, but for updates run we do.

**Comment by dustymabe** [comment] 2018-04-30 13:40
one example where an updates-testing run has qcows: https://kojipkgs.fedoraproject.org/compose/updates/Fedora-28-updates-testing-20180429.1/compose/AtomicHost/x86_64/images/

**Comment by sayanchowdhury** [comment] 2018-07-11 15:32
This feature has been pushed and deployed. Closing.

**Comment by abitrolly** [comment] 2018-07-13 17:31
Not closed yet.

**Comment by sayanchowdhury** [comment] 2018-07-19 18:23
Now confirmed that the issue is closed

**Closed as completed** 2018-07-19 18:22 UTC
